#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/packages/config/src/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

# a list of other known repositories we can talk to
uplinks:
  taobao:
    url: https://registry.npmmirror.com/
  npmjs:
    url: https://registry.npmjs.org/
  yarn:
    url:  https://registry.yarnpkg.com/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taobao

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/unpublish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: taobao

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true


listen: 0.0.0.0:4873

url_prefix: '/npm'

notify:
  method: POST
  headers: [{ 'Content-Type': 'application/json;charset=utf-8' }]
  endpoint: https://oapi.dingtalk.com/robot/send?access_token=xxxxx
  content: '{"msgtype":"actionCard", "actionCard": {"text": "package published: * {{ name }} * publisher name: * {{ publisher.name }} *  version: {{#each versions}} v{{version}}{{/each}} "}}'

# log settings
log:
  - { type: stdout, format: pretty, level: trace }
  #- {type: file, path: verdaccio.log, level: info}
